name: Pull request
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  pr-check:
    name: PR test for pdf-extractor
    runs-on: ubuntu-latest
    if: github.repository == 'ScientaNL/pdf-extractor'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
