name: Create release
on:
  release:
    types: [ created ]
jobs:
  npm-version-publish:
    name: NPM publish pdf-extractor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: NPM version release
        uses: ScientaNL/release-npm-github-action@1.2.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          npm-token: "${{ secrets.NPM_SCIENTA_TOKEN }}"
          repository-owner: "ScientaNL"
          npm-options: "{tag: 'latest', access: 'public'}"
