name: Create release
on:
  release:
    types: [ created ]
jobs:
  npm-version-publish:
    name: NPM publish pdf-extractor
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: ${{ !env.ACT }}
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: NPM version release
        uses: ScientaNL/release-npm-github-action@1.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          npm-token: "${{ secrets.NPM_SCIENTA_TOKEN }}"
          repository-owner: "ScientaNL"
          npm-options: "{tag: 'latest', access: 'public'}"
